openapi: 3.0.4
info:
  title: Swagger Expense Tracker - OpenAPI 3.0
  description: |-
     Это эндпойнты будущего RESTful-сервера проекта "Трекер трат"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.12
servers:
  - url: https://expensetracker.swagger.io/api/v3

tags:
  - name: expenses
    description: Операции с тратами

paths:
  /expenses:
    post:
      tags: [expenses]
      summary: Добавить новую трату
      description: Записывает информацию о новой трате в систему
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Expense'
      responses:
        '201':
          description: Трата успешно добавлена
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "Expense added"
                  expense_id:
                    type: string
                    example: "507f1f77bcf86cd799439011"
        '400':
          description: Неверный формат данных
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Конечная точка не найдена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /top-category:
    get:
      tags: [expenses]
      summary: Получить категорию с наибольшими тратами за месяц
      description: Возвращает категорию, на которую было потрачено больше всего денег за указанный месяц
      parameters:
        - name: month
          in: query
          description: Номер месяца (1-12)
          required: true
          schema:
            type: integer
            minimum: 1
            maximum: 12
            example: 5
      responses:
        '200':
          description: Успешный запрос
          content:
            application/json:
              schema:
                type: object
                properties:
                  category:
                    type: string
                    example: "Еда"
                  total:
                    type: number
                    format: float
                    example: 12500.50
        '400':
          description: Неверный параметр месяца
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Данные не найдены
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /largest-expense:
    get:
      tags: [expenses]
      summary: Получить самую крупную трату
      description: Возвращает самую крупную трату за указанный месяц и/или в указанной категории
      parameters:
        - name: month
          in: query
          description: Номер месяца (1-12)
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 12
            example: 5
        - name: category
          in: query
          description: Название категории
          required: false
          schema:
            type: string
            example: "Еда"
      responses:
        '200':
          description: Успешный запрос
          content:
            application/json:
              schema:
                type: object
                properties:
                  description:
                    type: string
                    example: "Продукты на неделю"
                  category:
                    type: string
                    example: "Еда"
                  amount:
                    type: number
                    format: float
                    example: 5500.75
                  date:
                    type: string
                    example: "04.05"
        '400':
          description: Неверные параметры запроса
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Данные не найдены
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Expense:
      type: object
      required:
        - description
        - category
        - amount
        - date
      properties:
        description:
          type: string
          description: Описание траты
          example: "Молоко"
        category:
          type: string
          description: Категория траты
          example: "Еда"
        amount:
          type: number
          format: float
          description: Сумма траты
          example: 110.00
        date:
          type: string
          description: Дата в формате ДД.ММ
          example: "04.05"
    Error:
      type: object
      properties:
        error:
          type: string
          description: Описание ошибки
          example: "Invalid data format"